

# Types of evidence synthesis (aka reviews)

## Review the pre-class assignment
- Grant and Booth (2009)'s Table 1 lists 14 types of reviews
  - Other perspectives, there are so many variations 
  - "48 review types were identified and categorised into seven families" Sutton et al. 2019^[Sutton, A. , Clowes, M. , Preston, L. and Booth, A. (2019), Meeting the review family: exploring review types and associated information retrieval requirements. Health Info Libr J, 36: 202-222., which has been published in final form at https://doi.org/10.1111/hir.12276.]

## What type of reviews are they?

- Stewart 2011 - systematic critical review

- Masson et al. 2020 - narrative review

- Wang et al. 2021 - critical review

- Li et al. 2024 - meta-analysis

## What did you think of the search strategies?

How did they compare to your homework 2?

- Stewart 2011 - systematic critical review

- Masson et al. 2020 - narrative review

- Wang et al. 2021 - critical review

- Li et al. 2024 - meta-analysis


## What we cover today

- Types of evidence synthesis
- What is reproducibility
- Reproducibility in reviews

## Broader terms
  - Evidence synthesis
  - Literature review
- Narrative review
  - Most [undergrad and beginning grad resources](https://teachbritannica.com/academic-toolkits/mastering-the-literature-review/) will be about this type
  - This is a perfectly good type of review!
- Systematic review
  - Scoping/mapping review (counts)
  - Meta-analysis (statistics beyond counts)
  - So many other types
- Structured or systematized review
  - When you don't have a full team (2+)
  
  
## What distinguishes a narrative review from these others?

- Formal structure

- Reproducibility

## What is reproducibility?

- Have you tried reproducing methods from a paper, review or empirical?


## How can we make a literature review reproducible?

- Ideas for what you need to write down

## PRISMA and other reporting frameworks

# Ok, let's make our own work more reproducible

## Searching quick review

- Take a look at your Homework 2 worksheet (we did it in class)

## Searching in depth

- This is a learned skill
- Places you can get, use, and cite existing searches

## Tools beyond Zotero

- [Covidence](covidence.org)

  - in one year pilot (12 months more if we don't renew)

  - Email me cmcurry@ou.edu to get an account

- [The Evidence Review Accelerator](https://tera-tools.com/)
